backend/locationApp/borrow/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class BorrowForm(FlaskForm):
  client = StringField('Klient name', validators=[DataRequired()])
  submit = SubmitField('Save borrow')

backend/locationApp/borrow/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect
from datetime import datetime
from locationApp import db
from locationApp.borrow.forms import BorrowForm
from locationApp.models import Borrow


borrow = Blueprint('borrow', __name__)



@borrow.route("/borrow-list", methods=['POST', 'GET'])
def borrow_list():
  borrows = Borrow.query.filter(Borrow.borrowed_to!= datetime.max).order_by(Borrow.id.desc())
  active = Borrow.query.filter(Borrow.borrowed_to >= datetime.utcnow()).first()
  return render_template('borrow_list.html', borrows=borrows, active=active)

@borrow.route("/borrow/new", methods=['POST', 'GET'])
def borrow_new():
  form = BorrowForm()
  if form.validate_on_submit():
    borrow = Borrow(client=form.client.data)
    db.session.add(borrow)
    db.session.commit()
    flash('Your borrow has been created, you are able to use it!', 'success')
    return redirect(url_for('borrow.borrow_list'))
  return render_template('borrow_new.html', form=form)

@borrow.route("/borrow/<int:borrow_id>", methods=['POST', 'GET'])
def borrow_view(borrow_id):
  borrow = Borrow.query.get_or_404(borrow_id)
  stoppable = borrow.borrowed_to >= datetime.utcnow()
  return render_template('borrow.html', borrow=borrow, stoppable=stoppable)

@borrow.route("/borrow/<int:borrow_id>/stop", methods=['POST', 'GET'])
def borrow_stop(borrow_id):
  borrow = Borrow.query.get_or_404(borrow_id)
  borrow.borrowed_to = datetime.utcnow()
  db.session.commit()
  flash('Your borrow has been stopped!', 'success')
  return redirect(url_for('main.index'))

@borrow.route("/borrow/<int:borrow_id>/delete", methods=['POST', 'GET'])
def borrow_delete(borrow_id):
  borrow = Borrow.query.get_or_404(borrow_id)
  db.session.delete(borrow)
  db.session.commit()
  flash('Your borrow has been deleted!', 'success')
  return redirect(url_for('borrow.borrow_list'))

backend/locationApp/main/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, abort
from datetime import datetime
from locationApp import db
from locationApp.models import Borrow
from locationApp.forms import KeyForm
from locationApp.models import LocationPoint, ApiKey, Borrow
from flask_login import current_user
from secrets import token_hex
import requests

main = Blueprint('main', __name__)


@main.route("/")
def index():
  active_borrow = Borrow.query.filter(Borrow.borrowed_to >= datetime.utcnow()).first()
  data = "" # To be filled probably
  return render_template('home.html', data=data, borrow=active_borrow)

@main.route("/about")
def about():
  return "<h1>Hello World about</h1>"





@main.route("/key-list", methods=['POST', 'GET'])
def key_list():
#  keys = ApiKey.query.filter_by(owner=current_user)
  keys = ApiKey.query.all()
#  active = Borrow.query.filter(Borrow.borrowed_to >= datetime.utcnow()).first()
  return render_template('key_list.html', keys=keys)

@main.route("/key/new", methods=['POST', 'GET'])
def key_new():
  form = KeyForm()
  if form.validate_on_submit():
    key = ApiKey(name=form.name.data, key=form.key.data, owner=current_user)
    db.session.add(key)
    db.session.commit()
    flash('Your key has been created, you are able to use it!', 'success')
    return redirect(url_for('main.key_list'))
  elif request.method == 'GET':
    form.key.data = token_hex(nbytes=16)
  return render_template('key_new.html', form=form)

@main.route("/key/<int:key_id>/delete", methods=['POST', 'GET'])
def key_delete(key_id):
  key = ApiKey.query.get_or_404(key_id)
  db.session.delete(key)
  db.session.commit()
  flash('Your key has been deleted!', 'success')
  return redirect(url_for('main.key_list'))

@main.route("/api/newpoint", methods=['POST', 'GET'])
def addPoint():
  if not ApiKey.query.filter_by(key=request.args.get('apikey')).first():
    abort(403)
  active_borrow = Borrow.query.filter(Borrow.borrowed_to >= datetime.utcnow()).first()
#  print(active_borrow)
  data = request.json
#  print(type(float(data['latitude'])))
#  print(data.latitude)
  location_point = LocationPoint(timestamp=datetime.now(), latitude=float(data['latitude']), longitude=float(data['longitude']), borrow=active_borrow)
  db.session.add(location_point)
  db.session.commit()
#  timestamp = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
#  latitude = db.Column(db.Float, nullable=False)
#  longitude = db.Column(db.Float, nullable=False)
#  borrow_id = db.Column(db.Integer, db.ForeignKey('borrow.id'), nullable=False) 
# print(content)
#  print(request.args.get('apikey'))
  return {'pointID': location_point.id}


@main.route("/test", methods=['POST', 'GET'])
def test():
  res = requests.post('http://localhost:5000/api/newpoint?apikey=b18bfe275cb7ea0007655d62c7fe39ee', json={"latitude":"12.34", "longitude": "56.78"})
  if res.ok:
    print(res.json())
  return 'success'

backend/locationApp/users/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request
from locationApp import db, bcrypt
from locationApp.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from locationApp.models import User, ApiKey
from flask_login import login_user, current_user, logout_user, login_required

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
  if current_user.is_authenticated:
    return redirect(url_for('main.index'))
  form = RegistrationForm()
  if form.validate_on_submit():
    hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
    user = User(username=form.username.data, email=form.email.data, password=hashed_password)
    db.session.add(user)
    db.session.commit()
    flash('Your account has been created, you are able to log in!', 'success')
    return redirect(url_for('users.login'))
  return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
  if current_user.is_authenticated:
    return redirect(url_for('main.index'))
  form = LoginForm()
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user and bcrypt.check_password_hash(user.password, form.password.data):
      login_user(user, remember=form.remember.data)
      next_page = request.args.get('next')
      if next_page:
        return redirect(next_page)
      return redirect(url_for('main.index'))
    else:
      flash(f'Login unsuccessfull !', 'danger')
  return render_template('login.html', title='Log in', form=form)

@users.route("/logout")
def logout():
  logout_user()
  return redirect(url_for('main.index'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
  form = UpdateAccountForm()
  keys = ApiKey.query.filter_by(owner=current_user).all()
  if form.validate_on_submit():
    current_user.username = form.username.data
    current_user.email = form.email.data
    db.session.commit()
    flash('Your account has been updated!', 'success')
    return redirect(url_for('users.account'))
  elif request.method == 'GET':
    form.username.data = current_user.username
    form.email.data = current_user.email
  return render_template('account.html', keys=keys, form=form)

backend/locationApp/templates/account.html
{% extends "layout.html" %}

{% block content %}

<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-6">
        <h1 class="title is-1">Hello {{ current_user.username }}</h1>
      </div>
      <div class="column is-6">
        <div class="box">
          <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form">
              <div class="field">
                {{ form.username.label(class='label') }}
        
        
                {% if form.username.errors %}
                  <div class="control has-icons-right">
                    {{ form.username(class='input is-danger') }}
                    <span class="icon is-small is-right">
                      <i class="fas fa-exclamation-triangle"></i>
                    </span>
                  </div>
                  {% for error in form.username.errors %}
                    <p class="help is-danger">{{ error }}</p>
                  {% endfor %}
                {% else %}
                  <div class="control">
                    {{ form.username(class='input') }}
                  </div>
                {% endif %}
              </div>
              <div class="field">
                {{ form.email.label(class='label') }}
        
                {% if form.email.errors %}
                  <div class="control has-icons-right">
                    {{ form.email(class='input is-danger') }}
                    <span class="icon is-small is-right">
                      <i class="fas fa-exclamation-triangle"></i>
                    </span>
                  </div>
                  {% for error in form.email.errors %}
                    <p class="help is-danger">{{ error }}</p>
                  {% endfor %}
                {% else %}
                  <div class="control">
                    {{ form.email(class='input') }}
                  </div>
                {% endif %}
        
              </div>
        
              <div class="field is-grouped">
                <div class="control">
                  {{ form.submit(class="button is-link") }}
                </div>
              </div>
              
              
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  {#
    <div class="columns is-centered mt-6">
      <div class="column is-4">
        <h2 class="title is-4">List of keys</h2>
        <ul>
          {% for key in keys %}
            <li>{{ key.name }}</li>
          {% endfor %}
        </ul>
      </div>
      <div class="column is-8">
        <form method="POST" action="" class="box">
          <h2 class="title is-4">New key</h2>
          {{ form.hidden_tag() }}
          {{ form.identifier(hidden=True, value='key_form') }}
          <fieldset class="form">
            <div class="field">
              {{ form.name.label(class='label') }}
              {% if form.name.errors %}
                <div class="control has-icons-right">
                  {{ form.name(class='input is-danger') }}
                  <span class="icon is-small is-right">
                    <i class="fas fa-exclamation-triangle"></i>
                  </span>
                </div>
                {% for error in form.name.errors %}
                  <p class="help is-danger">{{ error }}</p>
                {% endfor %}
              {% else %}
                <div class="control">
                  {{ form.name(class='input') }}
                </div>
              {% endif %}
    
            </div>
            <div class="field">
              {{ form.key.label(class='label') }}
    
              {% if form.key.errors %}
                <div class="control has-icons-right">
                  {{ form.key(class='input is-danger') }}
                  <span class="icon is-small is-right">
                    <i class="fas fa-exclamation-triangle"></i>
                  </span>
                </div>
                {% for error in form.key.errors %}
                  <p class="help is-danger">{{ error }}</p>
                {% endfor %}
              {% else %}
                <div class="control">
                  {{ form.key(class='input', disabled=True)  }}
                </div>
              {% endif %}
              
            </div>
            
    
            <div class="field is-grouped">
              <div class="control">
                {{ form.submit(class="button is-link") }}
              </div>
            </div>
            
            
          </fieldset>
        </form>
      </div>
    </div>
  #}
  
  </div>
</section>

  
{% endblock content %}

backend/locationApp/templates/borrow.html
{% extends "layout.html" %}

{% block content %}

<section class="section">
  <div class="container">
  <div class="columns is-centered mt-6">
    <div class="column is-4">
      <h2 class="title is-4">Borrow with client {{ borrow.client }} </h2>
      <div class="buttons">
        <a class="button is-danger" href="{{ url_for('borrow.borrow_delete', borrow_id=borrow.id) }}">Delete borrow</a>
        {% if stoppable %}
          <a class="button is-danger" href="{{ url_for('borrow.borrow_stop', borrow_id=borrow.id) }}">Stop borrow</a>
        {% endif %}
      </div>
      <p class="content">
        {{ borrow.borrowed_from }}
      </p>
      <p class="content">
        {{ borrow.borrowed_to }}
      </p>
      <p class="content">
        {{ borrow.points.length }}
      </p>
    </div>
  </div>
  </div>
</section>

  
{% endblock content %}

backend/locationApp/templates/borrow_list.html
{% extends "layout.html" %}

{% block content %}

<section class="section">
  <div class="container">
  <h1 class="title is-1">Hello {{ current_user.username }}</h1>
  <div class="columns is-centered mt-6">
    <div class="column is-6">
      {% if active %}
      <div class="box">
        <h2 class="title is-3">Current client is:</h2>
        Client name: <a href="{{ url_for('borrow.borrow_view', borrow_id=active.id) }}">{{ active.client }}</a><br>
        <a class="button is-danger" href="{{ url_for('borrow.borrow_stop', borrow_id=active.id) }}">Stop borrow</a>
      </div>
      {% else %}
        <a href="{{ url_for('borrow.borrow_new') }}" class="button is-primary is-large">Create new borrow</a>
      {% endif%}
    </div>
    <div class="column is-4">
      <h2 class="title is-4">List of clients</h2>
      <ul>
        {% for borrow in borrows %}
          <li> <a href="{{ url_for('borrow.borrow_view', borrow_id=borrow.id) }}">{{ borrow.client }}</a> (Borrowed until {{ borrow.borrowed_to.strftime('%Y-%m-%d %H:%m %z') }})</li>
        {% endfor %}
      </ul>
    </div>
  </div>
  </div>
</section>

  
{% endblock content %}

backend/locationApp/templates/borrow_new.html
{% extends "layout.html" %}

{% block content %}

<section class="section">
  <div class="container">
  <h1 class="title is-1">Hello {{ current_user.username }}</h1>
  <div class="columns is-centered mt-6">
    <div class="column is-6">
      <form method="POST" action="" class="box">
        <h2 class="title is-4">New Borrow</h2>
        {{ form.hidden_tag() }}
        
        <fieldset class="form">
          <div class="field">
            {{ form.client.label(class='label') }}
            {% if form.client.errors %}
              <div class="control has-icons-right">
                {{ form.client(class='input is-danger') }}
                <span class="icon is-small is-right">
                  <i class="fas fa-exclamation-triangle"></i>
                </span>
              </div>
              {% for error in form.client.errors %}
                <p class="help is-danger">{{ error }}</p>
              {% endfor %}
            {% else %}
              <div class="control">
                {{ form.client(class='input') }}
              </div>
            {% endif %}
          </div>
          
      
          <div class="field is-grouped">
            <div class="control">
              {{ form.submit(class="button is-link") }}
            </div>
          </div>
          
          
        </fieldset>
      </form>
    </div>
  </div>
  </div>
</section>

  
{% endblock content %}

backend/locationApp/templates/home.html
{% extends "layout.html" %}

{% block content %}

<section class="section">
  <div class="container">
    
  {% if borrow %}
    <p class="content mb-6">Current client is {{ borrow.client }}</p>
    {% for point in borrow.points %}
      {{ point.latitude }} {{ point.longitude }}
      <br>
    {% endfor %}
  {% else %}
    <p class="content mb-6">There is no current borrow</p>
  {% endif %}
  </div>
</section>

  
{% endblock content %}
  

backend/locationApp/templates/key_list.html
{% extends "layout.html" %}

{% block content %}

<section class="section">
  <div class="container">
    <div class="columns is-centered mt-6">
      <div class="column is-8">
        <h2 class="title is-4">List of keys</h2>
        {% if keys %}
        <table class="table is-striped">
          <thead>
            <th>Key name</th>
            <th>Key value</th>
            <th>Action</th>
          </thead>
          <tbody>
            {% for key in keys %}
              <tr>
                <td>{{ key.name }}</td>
                <td>{{ key.key }}</td>
                <td> <a href="{{ url_for('main.key_delete', key_id=key.id) }}" class="button is-danger">Delete key</a></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}  
          <p class="content">No keys active</p>
        {% endif %}
      </div>
      <div class="column is-4">
        <a href="{{ url_for('main.key_new')}}" class="button is-large is-primary">New key</a>
      </div>
    </div>

  
  </div>
</section>

  
{% endblock content %}

backend/locationApp/templates/key_new.html
{% extends "layout.html" %}

{% block content %}

<section class="section">
  <div class="container">
  <h1 class="title is-1">Hello {{ current_user.username }}</h1>
  <div class="columns is-centered mt-6">
    <div class="column is-6">
      <form method="POST" action="" class="box">
        <h2 class="title is-4">New key</h2>
        {{ form.hidden_tag() }}
        <fieldset class="form">
          <div class="field">
            {{ form.name.label(class='label') }}
            {% if form.name.errors %}
              <div class="control has-icons-right">
                {{ form.name(class='input is-danger') }}
                <span class="icon is-small is-right">
                  <i class="fas fa-exclamation-triangle"></i>
                </span>
              </div>
              {% for error in form.name.errors %}
                <p class="help is-danger">{{ error }}</p>
              {% endfor %}
            {% else %}
              <div class="control">
                {{ form.name(class='input') }}
              </div>
            {% endif %}
  
          </div>
          <div class="field">
            {{ form.key.label(class='label') }}
  
            {% if form.key.errors %}
              <div class="control has-icons-right">
                {{ form.key(class='input is-danger') }}
                <span class="icon is-small is-right">
                  <i class="fas fa-exclamation-triangle"></i>
                </span>
              </div>
              {% for error in form.key.errors %}
                <p class="help is-danger">{{ error }}</p>
              {% endfor %}
            {% else %}
              <div class="control">
                {{ form.key(class='input is-disabled', readonly=True)  }}
              </div>
            {% endif %}
            
          </div>
          
  
          <div class="field is-grouped">
            <div class="control">
              {{ form.submit(class="button is-link") }}
            </div>
          </div>
          
          
        </fieldset>
      </form>
    </div>
  </div>
  </div>
</section>

  
{% endblock content %}

backend/locationApp/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  {% if title %}
    <title>Location app - {{ title }}</title>
  {% else %}
    <title>Location app</title>
  {% endif %}

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
  
  {% include 'navbar.html' %}

<section class="section pt-6">
  <div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="notification is-{{ category }}">
          <button class="delete"></button>
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
  {% endwith%}

  {% block content%}
  {% endblock %}
  </div>
</section>
  

</body>
</html> 

backend/locationApp/templates/login.html
{% extends "layout.html" %}

{% block content %}

<section class="section">
  <div class="container">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form">
        <legend>Login here!</legend>
        <div class="field">
          {{ form.email.label(class='label') }}

          {% if form.email.errors %}
            <div class="control has-icons-right">
              {{ form.email(class='input is-danger') }}
              <span class="icon is-small is-right">
                <i class="fas fa-exclamation-triangle"></i>
              </span>
            </div>
            {% for error in form.email.errors %}
              <p class="help is-danger">{{ error }}</p>
            {% endfor %}
          {% else %}
            <div class="control">
              {{ form.email(class='input') }}
            </div>
          {% endif %}

        </div>
        <div class="field">
          {{ form.password.label(class='label') }}

          {% if form.password.errors %}
            <div class="control has-icons-right">
              {{ form.password(class='input is-danger') }}
              <span class="icon is-small is-right">
                <i class="fas fa-exclamation-triangle"></i>
              </span>
            </div>
            {% for error in form.password.errors %}
              <p class="help is-danger">{{ error }}</p>
            {% endfor %}
          {% else %}
            <div class="control">
              {{ form.password(class='input') }}
            </div>
          {% endif %}
          
        </div>
        <div class="field">
          
          {% if form.remember.errors %}
            <div class="control has-icons-right">
              <div class="control is-danger">
                {{ form.remember(class='checkbox is-danger') }}
                {{ form.remember.label(class='checkbox is-danger') }}
              </div>
            {% for error in form.remember.errors %}
              <p class="help is-danger">{{ error }}</p>
            {% endfor %}
          {% else %}
          <div class="control">
            {{ form.remember(class='checkbox') }}
            {{ form.remember.label(class='checkbox') }}
          </div>
          {% endif %}
          
        </div>

        <div class="field is-grouped">
          <div class="control">
            {{ form.submit(class="button is-link") }}
          </div>
        </div>
        
        
      </fieldset>
    </form>

    <div class="content">
      You can register here: <a href="{{ url_for('users.register') }}">Sign in</a>
    </div>
  </div>
</section>
  
{% endblock content %}
  

backend/locationApp/templates/navbar.html
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="{{ url_for('main.index')}}">
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      {% if current_user.is_authenticated %}
        <a class="navbar-item" href="{{ url_for('borrow.borrow_list')}}">
          Borrows
        </a>
        <a class="navbar-item" href="{{ url_for('main.key_list')}}">
          Keys
        </a>
      {% endif %}
      {# 
        <a class="navbar-item">
          Documentation
        </a>
      #}

    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          {% if current_user.is_authenticated %}
            <a class="button" href="{{ url_for('users.account')}}">
              <strong>My account</strong>
            </a>  
            <a class="button is-primary" href="{{ url_for('users.logout')}}">
              <strong>Log out</strong>
            </a>  
          {% else%}
            <a class="button is-primary" href="{{ url_for('users.register')}}">
              <strong>Sign up</strong>
            </a>
            <a class="button is-light" href="{{ url_for('users.login')}}">
              Log in
            </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</nav>

backend/locationApp/templates/register.html
{% extends "layout.html" %}

{% block content %}

<section class="section">
  <div class="container">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form">
        <legend>Join tobay!</legend>
        <div class="field">
          {{ form.username.label(class='label') }}


          {% if form.username.errors %}
            <div class="control has-icons-right">
              {{ form.username(class='input is-danger') }}
              <span class="icon is-small is-right">
                <i class="fas fa-exclamation-triangle"></i>
              </span>
            </div>
            {% for error in form.username.errors %}
              <p class="help is-danger">{{ error }}</p>
            {% endfor %}
          {% else %}
            <div class="control">
              {{ form.username(class='input') }}
            </div>
          {% endif %}
        </div>
        <div class="field">
          {{ form.email.label(class='label') }}

          {% if form.email.errors %}
            <div class="control has-icons-right">
              {{ form.email(class='input is-danger') }}
              <span class="icon is-small is-right">
                <i class="fas fa-exclamation-triangle"></i>
              </span>
            </div>
            {% for error in form.email.errors %}
              <p class="help is-danger">{{ error }}</p>
            {% endfor %}
          {% else %}
            <div class="control">
              {{ form.email(class='input') }}
            </div>
          {% endif %}

        </div>
        <div class="field">
          {{ form.password.label(class='label') }}

          {% if form.password.errors %}
            <div class="control has-icons-right">
              {{ form.password(class='input is-danger') }}
              <span class="icon is-small is-right">
                <i class="fas fa-exclamation-triangle"></i>
              </span>
            </div>
            {% for error in form.password.errors %}
              <p class="help is-danger">{{ error }}</p>
            {% endfor %}
          {% else %}
            <div class="control">
              {{ form.password(class='input') }}
            </div>
          {% endif %}
          
        </div>
        <div class="field">
          {{ form.confimPassword.label(class='label') }}

          {% if form.confimPassword.errors %}
            <div class="control has-icons-right">
              {{ form.confimPassword(class='input is-danger') }}
              <span class="icon is-small is-right">
                <i class="fas fa-exclamation-triangle"></i>
              </span>
            </div>
            {% for error in form.confimPassword.errors %}
              <p class="help is-danger">{{ error }}</p>
            {% endfor %}
          {% else %}
            <div class="control">
              {{ form.confimPassword(class='input') }}
            </div>
          {% endif %}
          
        </div>

        <div class="field is-grouped">
          <div class="control">
            {{ form.submit(class="button is-link") }}
          </div>
        </div>
        
        
      </fieldset>
    </form>

    <div class="content">
      You can login here: <a href="{{ url_for('users.login') }}">Sign in</a>
    </div>
  </div>
</section>
  
{% endblock content %}
  